### ISSUE TITLE
Multiselect doesn't work on MacOS

### ISSUE THREAD

**Issue by selfrefactor** [lukasbach/react-complex-tree#160]
Latest version `1.1.11` doesn't correctly recognize `command` button click. The bug was fixed by downgrading to `1.1.10`. What is odd is that if I use current state of the repo by copy/paste of `core` package, then it works. This means that it is not as much for the change of the code, as much as how the bundler(in my case CreateReactApp) is using the new version.

As additional info, it happens on `ControlledTreeEnvironment` component.

It is very much re-occurrence of https://github.com/lukasbach/react-complex-tree/issues/80

**Comment by lukasbach** [comment]
Since I don't have a mac, I can't really test or verify this, I don't see any reasons in the code why this would degrade between 1.1.10 and 1.1.11. I'm happy for anyone with a mac who could test this and maybe see where in the code this click gets lost. Note that, in the code, pretty much all that happens is

```typescript
export const isControlKey = (e: React.MouseEvent<any, any>) =>
  e.ctrlKey ||
  (navigator.platform.toUpperCase().indexOf('MAC') >= 0 && e.metaKey);
```

within an onClick event, otherwise the logic should be the same for windows and mac, and it seems to work under Windows, so maybe someone with a mac could already verify or report whether there is something not working with this snippet.

**Comment by Shaglock** [comment]
@lukasbach @selfrefactor on my mac it works correctly, I checked on my project locally and also checked in the storybook https://rct.lukasbach.com/storybook/?path=/story/core-basic-examples--actions, cmd + click works and also cmd+shift+click works, I don't see any problems

**Comment by selfrefactor** [comment]
thank you for the information. I will have access to Mac next week, so I will test it personally to assure that this weird issue is gone. I will write again once I know more.

**Comment by lukasbach** [comment]
Thanks both of you for your investigation, interested to see if it works for you @selfrefactor.

**Comment by selfrefactor** [comment]
I will close the issue, as I was unable to test it and I don't want to be reason for holding the issue open.
