### ISSUE TITLE
ClickArrowToExpand doesn't select the TreeItem.

### ISSUE THREAD

**Issue by floriancargoet** [lukasbach/react-complex-tree#2]
**Describe the bug**
When using ClickArrowToExpand, a single click on the whole TreeItem doesn't select it. 

**To Reproduce**
- `      defaultInteractionMode={InteractionMode.ClickArrowToExpand}`
- click on a node (but not on its arrow)
- observe that it is focused but not selected

**Expected behavior**
- A click on the arrow should expand (it does).
- A click on the rest of the item should select it (it doesn't).

**Screenshots**
![image](https://user-images.githubusercontent.com/110431/131515149-1ca4daed-7d27-4347-a172-cac3f5e3fc37.png)

Here the node "world" is selected because it has been expanded. I then clicked on the "The living room" node, and it was focused but not selected.

**Comment by lukasbach** [comment]
This was initially supposed to be like that, i.e. supposed to be primarily used in contexts where selecting doesn't make too much sense and items can only be focused, but I see how that creates confusion, especially with the blueprint renderers that don't show focused items unless in keyboard mode. I've changed it so that the `InteractionMode.ClickArrowToExpand` mode now also selects the item that is clicked on.

Btw, I've also adapted the interface s.t. custom interaction managers can be provided in place of the interaction mode identifier, if one wants to fully customize the interaction logic: https://rct.lukasbach.com/docs/guides/interaction-modes#custom-interaction-modes
