### ISSUE TITLE
Collision with react-dnd

### ISSUE THREAD

**Issue by rmapes** [lukasbach/react-complex-tree#282]
**Describe the bug**
When already using react-dnd in for drag and drop in other components, drag and drop in react-complex-tree does not work.

**To Reproduce**
1. Implement react-dnd elsewhere in the code
2. Implement a basic version of the tree from the getting started guide

**Expected behavior**
Drag and drop should work as expected

**Actual Behaviour**
Tree is rendered but does not respond to attempts to drag and drop with mouse

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOs
- Browser: Chrome
- Chrome Version 116.0.5845.96 

**Additional context**
A possible workaround would be to provide a configuration option to use react-dnd as the drag and drop controller within react-complex-tree, preventing collision

**Comment by lukasbach** [comment]
Hm, yeah I can't really figure out what causes the problem, react-dnd seems to overwrite some dnd events that rct needs, but I'm not sure..

**Comment by lukasbach** [comment]
I unfortunately don't see any actionable things to do here, since I am not sure if the issue comes from this library or react-dnd, and I'm not sure if this is still relevant. I'll close this for now, feel free to reopen if you have additional information on this or believe this can be fixed through changes in react-complex-tree.
