### ISSUE TITLE
Animation when node is opened and closed

### ISSUE THREAD

**Issue by piszczu4** [lukasbach/react-complex-tree#290]
Is it possible to add a custom animation to the node content when its opened and closed?

**Comment by lukasbach** [comment]
Opening transitions should be doable fairly easily, when a subtree is opened, its content is rendered in and you should be able to just add an animation to that with CSS.

Closing animations are probably quite a bit trickier, I'm not sure if that is possible since the subtree is directly unloaded when you close the subtree, so a CSS animation is probably not working then.

**Comment by Nishchit14** [comment]
Is there any quick example for the animation? I think it would help a lot to implement in tree open/close folders.

**Comment by lukasbach** [comment]
Since this came up in another issue, I've added a prop `shouldRenderChildren` to allow library consumers to also show a subtree content when it is already collapsed, to allow for rendering a collapse animation. Alongside that, I also implemented a sample implementation for expanding and collapsing animations. See [Demo](https://rct.lukasbach.com/storybook/?path=/story/core-basic-examples--animated-expanding-and-collapsing)
and [Demo Implementation](https://github.com/lukasbach/react-complex-tree/blob/main/packages/core/src/stories/BasicExamples.stories.tsx#L561) for details.
