### ISSUE TITLE
Arrow Direction Not Changing Based on Language/Orientation (RTL/LTR)

### ISSUE THREAD

**Issue by SyedMisbahUrRehman** [lukasbach/react-complex-tree#369]
I'm using React Complex Tree in my React application to display a tree view. The small arrows next to folders, which indicate expand/collapse functionality, are currently rendered in the Left-to-Right (LTR) direction.

However, when I switch the application language to _Arabic_ (Right-to-Left, RTL) or the device orientation changes, the arrow direction doesn't automatically adjust. This creates a visual inconsistency for users.

**Expected Behavior:**

The arrow direction should dynamically change based on the document's direction (RTL or LTR) to maintain a consistent user experience across languages and orientations.

**Looking For:**

Suggestions on the most effective way to handle dynamic arrow direction changes in React Complex Tree based on language and orientation.
Are there plans for built-in support for this functionality in future versions?

**Comment by lukasbach** [comment]
Hi, thanks for the report. Theoretically, since RCT allows library consumers to use a custom render implementation, this could be custom-implemented before. But since this wasn't possible with the default renderers, I've added a way to achieve this with the built-in renderers as of v2.4.3. See https://rct.lukasbach.com/docs/guides/accessibility#right-to-left-mode-rtl for details.

**Comment by SyedMisbahUrRehman** [comment]
Thanks a lot man. Much appreciated
